Standardize linting file and fix or ignore lots of linting errors
smallstep/certificates pull request #1031
Opened 2022-08-23 19:44 UTC by dopey

2022-08-23 22:15 UTC, maraino requested changes
Let's try to make this As-like methods internal or use types and errors.As.

2022-08-23 22:15 UTC, maraino commented on authority/provisioner/claims.go
> +	return c, err
If we really want this linter, we probably should do
```suggestion
	if err := c.Validate(); err != nil {
		return nil, err
	}
	return c, nil
```

2022-08-23 22:15 UTC, maraino commented on cas/apiv1/services.go
> +type ErrNotImplemented struct { //nolint:errname // ignore error name warning
We should rename it.

2022-08-24 05:46 UTC, dopey commented on api/render/render.go
> +}
I'm not entirely sure how I would do this. Even if I define a RenderableError type struct {}, how would I handle potential errors from outside packages. Those packages definitely won't be using our RenderableError type. Like here: https://github.com/smallstep/certificates/blob/b3b37400264d9e9200f0c49479501efe5fb6598b/errs/error.go#L257.

2022-09-21 20:10 UTC, closed without merging