Fixes pcscd permission issue
smallstep/certificates pull request #1491
Opened 2023-07-26 07:00 UTC by andrewmzhang

I raised this error in the discord: https://discord.com/channels/837031272227930163/841249977699401759/1132937016103936030 I also fixed an issue with building the image on a Raspberry Pi.

#### Name of feature:
Fixes pcscd permission in docker container. Adds a tag to the golang builder

#### Pain or issue this feature alleviates:
When the pcscd service is started (via `entrypoint.sh`) by a non-root user, 
the container cannot correctly access the yubikey (passed via the docker `--device` flag) 

The `bullseye` tag for the golang builder alleviates an issue when building the container on an OS that doesn't have the right GLIBC version for `step-ca` binary. I ran into this issue when building on a Raspberry Pi 4 running Ubuntu.

```
/usr/local/bin/step-ca: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/step-ca)
/usr/local/bin/step-ca: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/step-ca)

```

2023-07-26 07:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/certificates?pullRequest=1491) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/certificates?pullRequest=1491) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/certificates?pullRequest=1491) it.</sub>

2023-07-28 00:16 UTC, tashian requested changes
Thanks for your contribution! :D

2023-07-28 00:16 UTC, tashian commented on docker/Dockerfile.hsm
> +FROM golang:bullseye AS builder
The de facto `golang` will use the latest Debian, and we'd like to keep it this way.

```suggestion
FROM golang AS builder
```

2023-07-28 00:31 UTC, andrewmzhang commented
I'm going to close this PR for the time being. I can't reliable get Yubikey passthru to work.

2023-07-28 00:31 UTC, closed without merging