Allow Tokens for Renewing Certificates
smallstep/certificates pull request #2042
Opened 2024-10-23 02:52 UTC by hunoz

#### Name of feature: Provide Functionality for Tokens to be Used for Renewing Certificates

#### Pain or issue this feature alleviates: Currently, a provisioner doesn't allow for tokens to be used in the `provisioner.RenewWithToken` function as the audience is set to use `/1.0/sign`, which makes the token invalid for renewing certificates.

#### Why is this important to the project (if not answered above): Renewal of certificates via tokens issued with a provisioner is required for planned application usage.

#### Is there documentation on how to use this feature? If so, where?
None that I am aware of.

#### In what environments or workflows is this feature supported?
Any environments where this usage is planned or expected.

#### In what environments or workflows is this feature explicitly NOT supported (if any)?
None

#### Supporting links/other PRs/issues: N/A

💔Thank you!

2024-10-23 02:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/certificates?pullRequest=2042) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/certificates?pullRequest=2042) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/certificates?pullRequest=2042) it.</sub>

2024-10-23 02:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/certificates?pullRequest=2042) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/certificates?pullRequest=2042) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/certificates?pullRequest=2042) it.</sub>

2024-10-23 02:53 UTC, hunoz commented on ca/provisioner.go
> +	p.endpoint.ResolveReference(&url.URL{Path: "/1.0/renew"})
Need to amend PR, forgot to remove this.

2024-10-23 02:56 UTC, hunoz commented on ca/provisioner.go
> +	p.endpoint.ResolveReference(&url.URL{Path: "/1.0/renew"})
Removed.

2024-10-30 02:16 UTC, maraino requested changes
I don't really know what you're trying to do here. 

Without taking into account the rekeys, `step-ca` provides two different ways to renew an X.509 certificate:
* Using an mTLS connection with the certificate to renew.
* Making a request with an authorization token that contains the certificate embedded in the token and is signed by the private key of the certificate.

The token you are creating is a regular sign token with the audience changed. I would be surprised if that works.

2024-12-02 22:37 UTC, closed without merging