Begins to fix issue 87
smallstep/certificates pull request #440
Opened 2020-12-22 22:52 UTC by mkkeffeler

### Description
This is the start of enabling a by provisioner appended certificate to the bundles that get returned. 

I need help getting this to work. I believe the best configuration for our customers would be an attribute in ca.json like this (open to renaming, of course, or moving)

```
      "provisioners": [
         {
                "options": {
                    "x509": {
                        "templateFile": "templates/certs/x509/all.tpl",
			"AppendedCertsFile": "/Users/mkeffele/foo.crt2",
```

Where the contents of ``` /Users/mkeffele/foo.crt2 ``` is the cert they want appended.

This works almost completely, and should be a completely optional thing, but I can't get it working quite. When i replace the variable with a hardcoded filepath, I can get the bundle to return that new cert. I seem to be missing something about being able to pass in the value of what is in ca.json in that JSON to this function. Help appreciated!

Tests to come after.

2020-12-22 22:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/certificates?pullRequest=440) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/certificates?pullRequest=440) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/certificates?pullRequest=440) it.</sub>

2020-12-23 23:08 UTC, maraino commented
Hi @mkkeffeler, adding a custom issuer (intermediate) per provisioner is way more complicated. I would stick to supporting multiple intermediates in ca.json's `crt`, and using the `cas/softcas/softcas.go` to support them.

2020-12-23 23:11 UTC, maraino commented
From what we talked, this:
https://github.com/smallstep/certificates/blob/3e6137110bed7baf563b9559cd54d7398801c573/authority%2Fauthority.go#L167-L170

Should become something like:
```go
options.CertificateChain, err = pemutil.ReadCertificateBundle(a.config.IntermediateCert)
if err != nil {
	return err
}
```

2020-12-24 04:51 UTC, mkkeffeler commented
successfully built, passes tests, and works as expected by appending the full content of intermediate_ca.crt

2020-12-24 04:52 UTC, mkkeffeler commented
Worth noting, the actual cert for the intermediate CA needs to be at the top of the file (aka, first in the bundle)

2020-12-24 04:52 UTC, mkkeffeler commented
This seems to solve my issue when testing locally, as i can now get a cert with a full bundle back to my offline root CA. :)

2020-12-28 22:37 UTC, maraino requested changes
Hi @mkkeffeler Looks great, I've just added a couple of comments to address. 

Regarding your previous comment:
> Worth noting, the actual cert for the intermediate CA needs to be at the top of the file (aka, first in the bundle)

This is the expected behavior, it's possible to validate it, but we were not doing it before. It's probably worth doing it, as well as making sure the crt matches the private key. But there's no need to add it in this PR.

Have you tested it with multiple intermediates?

2020-12-28 22:37 UTC, maraino commented on cas/softcas/softcas.go
> +		case opts.CertificateChain == nil:
Here is safer to check for `len(opts.CertificateChain) == 0`

2020-12-28 22:37 UTC, maraino commented on cas/apiv1/options.go
> +	CertificateChain []*x509.Certificate
Fix comment, Issuer doesn't exist anymore.

2020-12-28 22:51 UTC, mkkeffeler commented
What do you mean multiple? I have tested actually returning a bundle, and a single cert, both are working. I tested it against multiple provisioners, meaning JWK and ACME.

2020-12-28 22:52 UTC, maraino commented
I meant using two intermediates, but I think you did.

2020-12-28 23:14 UTC, mkkeffeler commented
correct, I tested using 2 intermediates being returned in the bundle, as well as with 2 provisioners. your code update requests are completed as well :)

2020-12-28 23:44 UTC, mkkeffeler reviewed
Perfect.

2020-12-29 00:08 UTC, maraino commented
@mkkeffeler Looks good to me, but there are some formatting issues, can you run `make fmt` and push again.

2020-12-29 01:48 UTC, maraino approved these changes
Thanks @mkkeffeler LGTM

2020-12-29 01:49 UTC, merged