Log serial number as hex byte string
smallstep/certificates pull request #631
Opened 2021-07-09 20:55 UTC by hillu

This change should cause less confusion in JSON parser implementations that think that every number is a 64 bit float.

Close #630

2021-07-09 20:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/smallstep/certificates?pullRequest=631) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/smallstep/certificates?pullRequest=631) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/smallstep/certificates?pullRequest=631) it.</sub>

2021-07-12 20:51 UTC, hillu commented
The labeler/label error message does not tell me anything useful. What went wrong?

2021-07-12 20:53 UTC, dopey commented
@hillu Don't worry about that. It's just a job that's supposed to label the PR as `needs triage` for us. But Github made a change recently so that users outside the org no longer have the permission to run that job. Now we've gotta fix that.

2021-07-13 13:12 UTC, maraino requested changes
I think is better to convert the serial number to a string, so the logs show the same representation that we use in the DB.

@dopey What do you think?

2021-07-13 15:47 UTC, hillu commented
@maraino Logging the serial as a stringified decimal number fixes my problem, too. I chose the hexadecimal number because that's what OpenSSL uses in `x509 -text` output.

2021-07-13 15:58 UTC, maraino commented
`step certificate inspect` shows both, base 10 and base 16 (hex). I think commands like `step ca revoke` uses always the base 10 version so I think it makes more sense to use it here too.

A different question is if base 10 was the right decision for this.

2021-07-13 23:57 UTC, dopey commented
@maraino I was thinking the same thing. So, for the purpose of this PR I think we should change to decimal representation. That's what's used in the database and that's what's expected by the `step ca revoke --serial <#>` command. 

@hillu if you think a hex representation would be better more conventional, let's open up another issue to discuss that. A change like that would need some thought since it would break backward compatibility.

2021-07-14 10:08 UTC, hillu commented
I have opened a new PR #641 with a simple one-line patch and am closing this.

2021-07-14 10:08 UTC, closed without merging