Converts group and subgroup to lowercase for comparison.
smallstep/certificates pull request #699
Opened 2021-09-08 11:44 UTC by fofloinn

Fixes #679

### Description
This should fix the above issue by converting the ssh principals to lower case for group comparison.
Please note I'm not sure what needs to be done with adding a test for this so any guidance would be appreciated. 

Thank you!

2021-09-08 18:15 UTC, maraino requested changes

2021-09-08 18:15 UTC, maraino commented on authority/provisioner/sign_ssh_options.go
> +		if _, ok := visit[subgroupLower[i]]; !ok {
@fofloinn Can you just remove groupLower and subgroupLower, and just do
```
visit[strings.ToLower(group[I])] = struct{}{}
...
if _, ok := visit[strings.ToLower(subgroup[I])]; !ok {
```

2021-09-08 23:02 UTC, maraino commented on authority/provisioner/sign_ssh_options.go
> +		if _, ok := visit[subgroupLower[i]]; !ok {
I've just pushed this changes myself.

2021-09-08 23:04 UTC, maraino approved these changes
I've pushed my suggestion. Thanks for fixing this, these quick fixes are not our main priority, and we really appreciate the community fixing this.

2021-09-08 23:05 UTC, merged

2021-09-09 10:18 UTC, fofloinn commented
> I've pushed my suggestion. Thanks for fixing this, these quick fixes are not our main priority, and we really appreciate the community fixing this.

No problem at all @maraino, happy to help where I can.

2021-09-09 17:35 UTC, maraino commented
@fofloinn I think we should create a new GitHub project `Community` or something similar where we can group these types of changes that are not our priority and the community can contribute.