Add attribute to disable SSH Hosts list API
smallstep/certificates pull request #989
Opened 2022-07-28 06:31 UTC by dopey

Fixes #981

2022-07-29 19:41 UTC, hslatman commented
lgtm!

2022-07-29 19:41 UTC, hslatman approved these changes

2022-08-04 00:36 UTC, maraino requested changes

2022-08-04 00:36 UTC, maraino commented on authority/config/config.go
> +	DisableSSHHostsListAPI bool                  `json:"disableSSHHostsListAPI,omitempty"`
Can you change the name to something like `disableGetSSHHosts`?

2022-08-08 21:03 UTC, maraino approved these changes
lgtm

2022-08-08 21:15 UTC, merged